### PR TITLE
[scripts/welcome] add logo for Kali

### PR DESCRIPTION
**Pull request by lexisother**

### CODE REVIEW

**Comment by dmitmel** [comment]
I'm tempted to go with "no"

**Comment by phorcys420** [comment]
what about backtrack !!??!? 😡😡🤬🤬

**Comment by thgeraads** [comment]
I have to use a Kali VM for school (pain) and using the command line without dotfiles is absolutely unusable. /s?

What's your point in excluding Kali?

**Comment by dmitmel** [comment]
Relax, this was a joke. I will answer your questions though:

> what about backtrack !!??!?

I don't understand what you mean.

> I have to use a Kali VM for school (pain) and using the command line without dotfiles is absolutely unusable.

My condolences. I recommend [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh). It's easy to setup and is maintained by a community.

> What's your point in excluding Kali?

I don't use it.

Anyway, @lexisother, I have added options to the welcome script for adding logo search directories, you may use it in your fork (for example, by aliasing `welcome` to `welcome --extra-logo-dir ${dotfiles_dir}/distro-logos/`). Logos of distros I don't use is not something I want to keep here.

@thgeraads and @phorcys420, please see the README of this repository.

Also, @phorcys420, who are you? I know only who @thgeraads is. Have we met?

**Comment by lexisother** [comment]
Thanks for the option!
(you haven't met Phorcys, they're a friend)

**Comment by phorcys420** [comment]
> Relax, this was a joke. I will answer your questions though:

This was a joke too, dw. Backbox though ?

> Also, @phorcys420, who are you?

As lexi said, one of her friends (and that pfp isnt me just incase)

**Pull request closed without merging**
